server:
  port: 9090

spring:
  application:
    name: tsumi-feign-example

# TsumiFeign 配置
tsumi:
  feign:
    okhttp:
      connect-timeout: 5000
      read-timeout: 10000
      write-timeout: 10000
      connection-pool:
        max-idle-connections: 200
        keep-alive-duration: 300
    client:
      log-level: BASIC
      retry-enabled: true
      max-retries: 3
    loadbalancer:
      strategy: round-robin
      enabled: true

logging:
  level:
    root: INFO
    fun.hatsumi: DEBUG
